### PR TITLE
[#826] Replace libcheck with MCTF testing framework

### LINKED ISSUE #826: Test: Come up with a new testing framework
libcheck isn't really working out.

Create a simple testing framework that will handle flow like

```
MCTF_START("my function")
   mctf_assert(x == y, "x and y are not equal", error);

   // Cleanup of x 
   // Cleanup of xy
   return true;

error:
   // Cleanup of x 
   // Cleanup of xy
   return false;
MCTF_END()
```

If you are willing to take this feature on, create a forum thread about so everybody can give feedback. Thanks !

### PR DESCRIPTION
**Pull request by shashidhar-bm**
- closes #826

Replaces libcheck with a new Minimalist C Test Framework (MCTF) to simplify testing infrastructure and remove external dependencies.

### CODE REVIEW

**Comment by shashidhar-bm** [comment]
@jesperpedersen  I've implemented the core framework and migrated the deque tests as a proof of concept—I will continue with the remaining tests once I receive feedback on this approach.

<details>
<summary><b>Detailed Test Output (./test/check_mctf.sh)</b></summary>

```text
Container port is set to: 6432
Building PostgreSQL 17 image if necessary
[sudo] password for shashidhar: 
Image pgmoneta-test-postgresql17-rocky9 exists, skip building
Preparing the pgmoneta directory
Building pgmoneta
-- The C compiler identification is Clang 18.1.3
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- pgmoneta 0.20.0
-- Build type is Debug
-- System is Linux
-- Performing Test COMPILER_SUPPORTS_C17
-- Performing Test COMPILER_SUPPORTS_C17 - Success
-- Performing Test COMPILER_SUPPORTS_SSE42
-- Performing Test COMPILER_SUPPORTS_SSE42 - Success
-- Performing Test HAVE_CRC32_SSE42
-- Performing Test HAVE_CRC32_SSE42 - Success
-- CPU have -msse4.2, defined HAVE_CRC32_SSE42
-- CRC32C implementation will use SSE 4.2
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for module 'check'
--   Found check, version 0.15.2
-- Found Check: /usr/include  
-- check found
-- Found Docker: /usr/bin/docker  
-- Could NOT find Podman (missing: PODMAN_EXECUTABLE) 
-- Docker or podman found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.3")  
-- zlib found
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- bzip2 found
-- Found Zstd: /usr/lib/x86_64-linux-gnu/libzstd.so  
-- zstd found
-- Found Lz4: /usr/lib/x86_64-linux-gnu/liblz4.so  
-- lz4 found
-- Found Libev: /usr/lib/x86_64-linux-gnu/libev.so (found suitable version "4.33", minimum required is "4.11") 
-- libev found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.13")  
-- OpenSSL found
-- Found LibArchive: /usr/lib/x86_64-linux-gnu/libarchive.so (found version "3.7.2") 
-- libarchive found
-- Found Libssh: /usr/lib/x86_64-linux-gnu/libssh.so  
-- libssh found
-- Found LibYAML: /usr/lib/x86_64-linux-gnu/libyaml.so  
-- LibYAML found
-- Found THREAD: /usr/lib/x86_64-linux-gnu/libpthread.a  
-- pthread found
-- libatomic found
-- Found Systemd: /usr/lib/x86_64-linux-gnu/libsystemd.so  
-- systemd found
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Coverage tools found
-- Performing Test HAS_NO_OMIT_FRAME_POINTER
-- Performing Test HAS_NO_OMIT_FRAME_POINTER - Success
-- Performing Test HAS_WEXTRA
-- Performing Test HAS_WEXTRA - Success
-- Performing Test HAS_NO_SIGN_COMPARE
-- Performing Test HAS_NO_SIGN_COMPARE - Success
-- Performing Test HAS_FORMAT
-- Performing Test HAS_FORMAT - Success
-- Performing Test HAS_FORMAT_SECURITY
-- Performing Test HAS_FORMAT_SECURITY - Success
-- Performing Test HAS_STACKPROTECTOR_STRONG
-- Performing Test HAS_STACKPROTECTOR_STRONG - Success
-- Performing Test HAS_DYNAMIC
-- Performing Test HAS_DYNAMIC - Success
-- Performing Test HAS_PIC
-- Performing Test HAS_PIC - Success
-- Performing Test HAS_LINKER
-- Performing Test HAS_LINKER - Success
-- Performing Test LINKER_HAS_RELRO
-- Performing Test LINKER_HAS_RELRO - Failed
-- Performing Test LINKER_HAS_NOW
-- Performing Test LINKER_HAS_NOW - Failed
-- Configuring done (4.9s)
-- Generating done (0.1s)
-- Build files have been written to: /home/shashidhar/project/pgmoneta/build
[  1%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/backup.c.o
[  1%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/aes.c.o
[  2%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/archive.c.o
[  4%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/bzip2_compression.c.o
[  4%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/brt.c.o
[  6%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/art.c.o
[  6%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/cmd.c.o
[  6%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/compresssion.c.o
[  7%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/configuration.c.o
[  8%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/csv.c.o
[  9%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/delete.c.o
[  9%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/deque.c.o
[ 10%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/extension.c.o
[ 11%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/gzip_compression.c.o
[ 12%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/http.c.o
[ 12%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/info.c.o
[ 13%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/json.c.o
[ 14%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/keep.c.o
[ 15%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/link.c.o
[ 15%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/logging.c.o
[ 16%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/lz4_compression.c.o
[ 17%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/management.c.o
[ 18%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/manifest.c.o
[ 18%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/memory.c.o
[ 19%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/message.c.o
[ 20%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/network.c.o
[ 21%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/pg_control.c.o
[ 21%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/prometheus.c.o
[ 22%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/remote.c.o
[ 23%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/restore.c.o
[ 24%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/retention.c.o
[ 25%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/se_azure.c.o
[ 25%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/se_local.c.o
[ 26%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/se_s3.c.o
[ 27%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/se_ssh.c.o
[ 28%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/security.c.o
[ 28%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/server.c.o
[ 29%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/shmem.c.o
[ 30%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/status.c.o
[ 31%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/tablespace.c.o
[ 31%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/utf8.c.o
[ 32%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/utils.c.o
[ 33%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/value.c.o
[ 34%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/verify.c.o
[ 34%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wal.c.o
[ 35%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile.c.o
[ 36%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/relpath.c.o
[ 37%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_brin.c.o
[ 37%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_btree.c.o
[ 38%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_clog.c.o
[ 39%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_commit_ts.c.o
[ 40%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_database.c.o
[ 40%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_generic.c.o
[ 41%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_gin.c.o
[ 42%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_gist.c.o
[ 43%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_hash.c.o
[ 43%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_heap.c.o
[ 44%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_logicalmsg.c.o
[ 45%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_mxact.c.o
[ 46%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_relmap.c.o
[ 46%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_replorigin.c.o
[ 47%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_seq.c.o
[ 48%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_spgist.c.o
[ 49%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_standby.c.o
[ 50%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_storage.c.o
[ 50%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_tablespace.c.o
[ 51%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_xact.c.o
[ 52%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rm_xlog.c.o
[ 52%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/wal_reader.c.o
[ 53%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/rmgr.c.o
[ 54%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/walfile/wal_summary.c.o
[ 55%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_archive.c.o
[ 56%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_backup.c.o
[ 56%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_backup_incremental.c.o
[ 57%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_bzip2.c.o
[ 58%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_cleanup.c.o
[ 59%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_delete.c.o
[ 59%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_encryption.c.o
[ 60%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_extra.c.o
[ 61%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_gzip.c.o
[ 62%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_hot_standby.c.o
[ 62%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_link.c.o
[ 63%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_lz4.c.o
[ 64%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_manifest.c.o
[ 65%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_permissions.c.o
[ 65%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_restore.c.o
[ 66%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_retention.c.o
[ 67%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_sha256.c.o
[ 68%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_sha512.c.o
[ 68%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_verify.c.o
[ 69%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/wf_zstd.c.o
[ 70%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/workers.c.o
[ 71%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/workflow.c.o
[ 71%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/yaml_utils.c.o
[ 72%] Building C object src/CMakeFiles/pgmoneta.dir/libpgmoneta/zstandard_compression.c.o
[ 73%] Linking C shared library libpgmoneta.so
[ 73%] Built target pgmoneta
[ 74%] Building C object src/CMakeFiles/pgmoneta-walinfo-bin.dir/walinfo.c.o
[ 75%] Building C object src/CMakeFiles/pgmoneta-cli-bin.dir/cli.c.o
[ 75%] Building C object src/CMakeFiles/pgmoneta-bin.dir/main.c.o
[ 77%] Building C object src/CMakeFiles/pgmoneta-walfilter-bin.dir/walfilter.c.o
[ 77%] Building C object test/CMakeFiles/pgmoneta-test.dir/runner.c.o
[ 78%] Building C object src/CMakeFiles/pgmoneta-admin-bin.dir/admin.c.o
[ 79%] Building C object test/CMakeFiles/pgmoneta-test.dir/libpgmonetatest/mctf.c.o
[ 79%] Building C object test/CMakeFiles/pgmoneta-mctf-test.dir/runner_mctf.c.o
[ 79%] Building C object test/CMakeFiles/pgmoneta-test.dir/libpgmonetatest/tsclient.c.o
[ 80%] Building C object test/CMakeFiles/pgmoneta-mctf-test.dir/libpgmonetatest/mctf.c.o
[ 81%] Building C object test/CMakeFiles/pgmoneta-test.dir/libpgmonetatest/tscommon.c.o
[ 82%] Building C object test/CMakeFiles/pgmoneta-mctf-test.dir/testcases/test_deque_mctf.c.o
[ 83%] Linking C executable pgmoneta-admin
[ 84%] Building C object test/CMakeFiles/pgmoneta-mctf-test.dir/libpgmonetatest/tscommon.c.o
[ 85%] Linking C executable pgmoneta-walfilter
[ 86%] Linking C executable pgmoneta-walinfo
[ 87%] Linking C executable pgmoneta-cli
[ 88%] Building C object test/CMakeFiles/pgmoneta-test.dir/libpgmonetatest/tswalutils/tswalutils_17.c.o
[ 89%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_art.c.o
[ 89%] Building C object test/CMakeFiles/pgmoneta-mctf-test.dir/libpgmonetatest/tsclient.c.o
[ 90%] Linking C executable pgmoneta
[ 90%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_backup.c.o
[ 90%] Built target pgmoneta-admin-bin
[ 91%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_brt_io.c.o
[ 91%] Built target pgmoneta-walinfo-bin
[ 92%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_delete.c.o
[ 93%] Linking C executable pgmoneta-mctf-test
[ 93%] Built target pgmoneta-walfilter-bin
[ 94%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_deque.c.o
[ 94%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_deque_mctf.c.o
[ 94%] Built target pgmoneta-cli-bin
[ 95%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_http.c.o
[ 96%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_json.c.o
[ 97%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_restore.c.o
[ 97%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_server_api.c.o
[ 97%] Built target pgmoneta-bin
[ 98%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_utils.c.o
[ 98%] Built target pgmoneta-mctf-test
[ 99%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_wal_summary.c.o
[100%] Building C object test/CMakeFiles/pgmoneta-test.dir/testcases/test_wal_utils.c.o
[100%] Linking C executable pgmoneta-test
[100%] Built target pgmoneta-test
Start PostgreSQL 17 container
7c8f3ec139dac87c299bef95157fa7d9d43e3d3b85943977e0e05843e0575115
Checking PostgreSQL 17 container readiness
Wait for 10 seconds and retry
PostgreSQL 17 is ready!
Initialize pgmoneta
Creating pgmoneta.conf and pgmoneta_users.conf inside /tmp/pgmoneta-test/base/conf ... ok
Add test configuration to pgmoneta.conf ... ok
Header:
  ClientVersion: 0.20.0
  Command: 25
  Compression: 0
  Encryption: 0
  Output: 0
  Timestamp: 20260108124548
Outcome:
  Status: true
  Time: 00:00:0.0148
Response:
  Users:
    - repl
Add user repl to pgmoneta_users.conf file ... ok
Keep a sample pgmoneta configuration

export PGMONETA_TEST_BASE_DIR=/tmp/pgmoneta-test/base
export PGMONETA_TEST_CONF=/tmp/pgmoneta-test/base/conf/pgmoneta.conf
export PGMONETA_TEST_CONF_SAMPLE=/tmp/pgmoneta-test/base/conf/pgmoneta.conf.sample
export PGMONETA_TEST_USER_CONF=/tmp/pgmoneta-test/base/conf/pgmoneta_users.conf
export PGMONETA_TEST_RESTORE_DIR=/tmp/pgmoneta-test/base/restore
Execute MCTF Testcases
Clean up any existing pgmoneta processes
Killing existing pgmoneta processes
Cleaning up shared memory segments
Starting pgmoneta server in daemon mode
Wait for pgmoneta to be ready
pgmoneta server started ... ok
Start running MCTF tests

=== Running MCTF Tests ===
Total tests to run: 9

[RUN] test_deque_sort
[PASS] test_deque_sort
[RUN] test_deque_iterator_remove
[PASS] test_deque_iterator_remove
[RUN] test_deque_iterator_read
[PASS] test_deque_iterator_read
[RUN] test_deque_add_with_config_and_get
[PASS] test_deque_add_with_config_and_get
[RUN] test_deque_remove
[PASS] test_deque_remove
[RUN] test_deque_clear
[PASS] test_deque_clear
[RUN] test_deque_add_poll_last
[PASS] test_deque_add_poll_last
[RUN] test_deque_add_poll
[PASS] test_deque_add_poll
[RUN] test_deque_create
[PASS] test_deque_create

=== Test Summary ===
Total tests: 9
Passed: 9
Failed: 0

Clean up
Shutdown pgmoneta
Header:
  ClientVersion: 0.20.0
  Command: shutdown
  Compression: zstd
  Encryption: aes-256-cbc
  Output: text
  Timestamp: 20260108124601
Outcome:
  Status: true
  Time: 00:00:0.0000
Request: {}
Clean Test Resources
Coverage tools (llvm-profdata, llvm-cov) not found, skipping coverage report generation
Logs --> /tmp/pgmoneta-test/log, /tmp/pgmoneta-test/pg_log
Removing postgres 17 container
pgmoneta-test-postgresql17
pgmoneta-test-postgresql17
Unsetting environment variables

File: test/testcases/test_deque_mctf.c [hunk 1]
```diff
@@ -0,0 +1,453 @@
...
+   MCTF_ASSERT_INT_EQ(dq->size, 0, "deque size should be 0", cleanup);
+
+cleanup:
+   if (dq)
+   {
+      pgmoneta_deque_destroy(dq);
+   }
+   pgmoneta_test_teardown();
+   MCTF_FINISH();
+}
```
Comment (shashidhar-bm) [inline test/testcases/test_deque_mctf.c]: **On failure:**
`MCTF_ASSERT` fails → `goto cleanup` → cleanup runs → `MCTF_FINISH()` returns line number

**On pass:**  
All assertions pass → sequential execution → falls through to `cleanup:` label → cleanup runs → `MCTF_FINISH()` returns 0

**Comment by jesperpedersen** [comment]
@ShashidharM0118 Just start to replace `check.sh` and friends - at the end we need a pull request without a dependency on libcheck

**Comment by jesperpedersen** [comment]
@ShashidharM0118 Please, work with @sksingh2005 (#849) and @sommye-ctr (#850) for additional requirements

**Comment by jesperpedersen** [comment]
@ShashidharM0118 Remember, https://github.com/pgmoneta/pgmoneta/blob/main/doc/DEVELOPERS.md#authors

**Comment by shashidhar-bm** [comment]
> @ShashidharM0118 Just start to replace `check.sh` and friends - at the end we need a pull request without a dependency on libcheck

sure, i'll do that

**Comment by jesperpedersen** [comment]
@ShashidharM0118 Remember, to squash - and see https://github.com/pgmoneta/pgmoneta/blob/main/CONTRIBUTING.md#code-style

**Comment by jesperpedersen** [comment]
@shashidhar-bm See https://github.com/pgmoneta/pgmoneta/blob/main/CONTRIBUTING.md#code-style - or the output from the CI

**Comment by shashidhar-bm** [comment]
> @shashidhar-bm See https://github.com/pgmoneta/pgmoneta/blob/main/CONTRIBUTING.md#code-style - or the output from the CI

It turns out I unknowingly had the wrong version of `clang-format `😅, but I think it is fixed now.

**Comment by jesperpedersen** [comment]
@shashidhar-bm Good progress ! I committed the error you found in `message.c` - remember to keep rebasing such that you get all fixes in

**Comment by jesperpedersen** [comment]
@shashidhar-bm I'm not looking at the code, but you have

```
[RUN] test_deque_sort
[PASS] test_deque_sort
```

Maybe

```
test_deque_sort (HH:mm:ss,SSS) [PASS]
```

such that each test case only takes only line, and we know how long it took to execute...

**Comment by shashidhar-bm** [comment]
@jesperpedersen I've updated it, and it's looking much better now!

**Comment by shashidhar-bm** [comment]
I think the PR is ready for review now. I'm curious to see how the workflow runs turn out!

**Comment by jesperpedersen** [comment]
@shashidhar-bm Looks like a good start !

**Comment by jesperpedersen** [comment]
@shashidhar-bm Begin on removing libcheck from the documentation, and update it with MCTF information

File: test/CMakeLists.txt [hunk 2]
```diff
@@ -111,15 +111,37 @@ if (check)
       endif()
     endif()
   endif()
+
+  # Build MCTF-based test (replaces Check)
+  # FILE(GLOB_RECURSE SOURCE_FILES "libpgmonetatest/*.c" "testcases/*.c")
+  FILE(GLOB_RECURSE SOURCE_FILES "libpgmonetatest/*.c")
+  # Explicitly list MCTF test files to avoid linking issues with legacy Check tests
```
Comment (Jubilee101) [inline test/CMakeLists.txt]: Can you elaborate on the linking issue? Why can't we wild card this? Can we do it later at least?

File: test/check.sh [hunk 3]
```diff
@@ -314,32 +306,61 @@ unset_pgmoneta_test_variables() {
...
+         sleep 3
+      fi
+      if pgrep -f pgmoneta >/dev/null 2>&1; then
+         echo "Killing existing pgmoneta processes"
+         pkill -9 -f pgmoneta || true
+         sleep 2
+      fi
+      rm -f "/tmp/pgmoneta.localhost.pid"
+      
+      echo "Cleaning up shared memory segments"
```
Comment (Jubilee101) [inline test/check.sh:339]: Can you do the same in cleanup as well?

File: test/include/mctf.h [hunk 4]
```diff
@@ -0,0 +1,215 @@
...
+
+/* Macros for test functions */
+
+/**
+ * Assert a condition, jump to error label on failure
+ * @param condition The condition to check
+ * @param message Error message
+ * @param error_label Label to jump to on failure
+ */
+#define MCTF_ASSERT(condition, message, error_label) \
```
Comment (Jubilee101) [inline test/include/mctf.h]: Where is the message used? Also we need to support printf-style formatting

**Comment by jesperpedersen** [comment]
@shashidhar-bm Especially the "Test" chapter in the documentation, and list what MCTF can do and can't - so we can get people to contribute test cases in an easy way

File: test/include/mctf.h [hunk 5]
```diff
@@ -0,0 +1,215 @@
...
+   const char* test_name;
+   bool passed;
+   bool skipped;
+   int error_code;
+} mctf_result_t;
+
+/* Test runner state */
+typedef struct mctf_runner
+{
+   mctf_test_t* tests;
```
Comment (Jubilee101) [inline test/include/mctf.h]: Do you think we can group them by tested modules/files? Current structure is a bit flat for me.

File: test/libpgmonetatest/tscommon.c [hunk 6]
```diff
@@ -121,18 +125,49 @@ pgmoneta_test_environment_destroy(void)
...
 pgmoneta_test_add_backup_chain(void)
 {
+   int ret = 0;
    pgmoneta_test_setup();
-   assert((!pgmoneta_tsclient_backup("primary", NULL)));
-   assert(!pgmoneta_tsclient_backup("primary", "newest"));
-   assert(!pgmoneta_tsclient_backup("primary", "newest"));
+   
+   ret = pgmoneta_tsclient_backup("primary", NULL);
+   if (ret != 0)
```
Comment (Jubilee101) [inline test/libpgmonetatest/tscommon.c]: we prefer `if (pgmoneta_tsclient_backup("primary", NULL))`

**Comment by jesperpedersen** [comment]
@shashidhar-bm Some times we get stuff like

```
pgmoneta-test: /home/runner/work/pgmoneta/pgmoneta/test/libpgmonetatest/tscommon.c:134: void pgmoneta_test_add_backup_chain(void): Assertion `!pgmoneta_tsclient_backup("primary", "newest")' failed.
./test/check.sh: line 325:  6644 Aborted                 (core dumped) $TEST_DIRECTORY/pgmoneta-test
```

That doesn't help much -- maybe have a signal handler that can give more information (pgmoneta_backtrace, and friends)

File: test/testcases/test_backup.c [hunk 7]
```diff
@@ -27,78 +27,97 @@
...
+   ret = pgmoneta_test_backup("primary", NULL);
+   if (ret != 0)
+   {
+      pgmoneta_test_basedir_cleanup();
+      MCTF_SKIP();
+   }
+
+cleanup:
+   pgmoneta_test_basedir_cleanup();
+   MCTF_FINISH();
```
Comment (Jubilee101) [inline test/testcases/test_backup.c:55]: Would be nice if we can make MCTF_FINISH by default, or at least somewhat more mandatory.

File: test/libpgmonetatest/tscommon.c [hunk 8]
```diff
@@ -121,18 +125,49 @@ pgmoneta_test_environment_destroy(void)
...
+   {
+      pgmoneta_log_error("pgmoneta_test_add_backup_chain: full backup failed");
```
Comment (Jubilee101) [inline test/libpgmonetatest/tscommon.c]: assert or print is better, if backup failed during setup we need to know immediately, without having to look at the log. If you can use your assert that would be great, I couldn't because check requires ck_assert to be inside a test, not prior to it.

File: test/libpgmonetatest/tscommon.c [hunk 9]
```diff
@@ -121,18 +125,49 @@ pgmoneta_test_environment_destroy(void)
...
+      pgmoneta_test_teardown();
```
Comment (Jubilee101) [inline test/libpgmonetatest/tscommon.c]: You should have the error section and goto the teardown instead.

File: test/libpgmonetatest/tscommon.c [hunk 10]
```diff
@@ -121,18 +125,49 @@ pgmoneta_test_environment_destroy(void)
...
+      return;
+   }
+   
+   sleep(2);
```
Comment (Jubilee101) [inline test/libpgmonetatest/tscommon.c]: pgmoneta_tsclient_backup already has sleep(1)

File: test/libpgmonetatest/tscommon.c [hunk 11]
```diff
@@ -223,3 +279,53 @@ pgmoneta_test_execute_query(int srv, SSL* ssl, int skt, char* query, struct quer
 
    return 1;
 }
+
+void
+pgmoneta_test_cleanup_ssl(SSL** ssl)
```
Comment (Jubilee101) [inline test/libpgmonetatest/tscommon.c]: I'll allow these functions for now. But please do a sweep and check if some of them are only restricted to certain test files, if so we should remove them from common.

File: test/include/mctf.h (hunk 5 above)
Comment (shashidhar-bm) [reply test/include/mctf.h]: @Jubilee101 , thinking to group them into modules
and display something like this?
```
=== Running MCTF Tests ===
Total tests to run: 89

--- backup ---
  test_pgmoneta_backup_full (00:00:01,234) [PASS]
  test_pgmoneta_backup_incremental_basic (00:00:02,456) [PASS]

--- delete ---
  test_pgmoneta_delete_full (00:00:00,789) [PASS]
  ...
```

Comment (Jubilee101) [reply test/include/mctf.h]: Looks good~ Also when filtering, module probably needs to be specified too.

Comment (jesperpedersen) [reply test/include/mctf.h]: @shashidhar-bm I agree, it should be full test suite, module test suite or single test case

File: test/CMakeLists.txt (hunk 2 above)
Comment (shashidhar-bm) [reply test/CMakeLists.txt]: Thank you for pointing this out :)
The explicit listing helped me in the middle to verify every time I replaced a test file to MCTF, but in the end I forgot to wildcard this.

File: test/libpgmonetatest/tscommon.c (hunk 11 above)
Comment (shashidhar-bm) [reply test/libpgmonetatest/tscommon.c]: I've moved these functions to `test_wal_summary.c` since they are only used in that test file.

File: test/testcases/test_backup.c (hunk 7 above)
Comment (shashidhar-bm) [reply test/testcases/test_backup.c:55]: @Jubilee101, I explored few ways, but couldn't find a clean solution. All tests currently use it explicitly. Do you have any suggestions on this?

File: test/include/mctf.h (hunk 4 above)
Comment (shashidhar-bm) [reply test/include/mctf.h]: now I've defined custom messages that are displayed in the test summary for failed test cases.
like,
```
Failed tests:
  - test_pgmoneta_backup_full (error code: 123) - backup count mismatch
  - test_pgmoneta_delete_backup (error code: 456) - failed to delete backup directory
 ```
does this look good?

Comment (jesperpedersen) [reply test/include/mctf.h]: @shashidhar-bm Yes, that looks good

File: test/testcases/test_backup.c (hunk 7 above)
Comment (jesperpedersen) [reply test/testcases/test_backup.c:55]: @shashidhar-bm I think explicit is ok for now

File: doc/TEST.md [hunk 12]
```diff
@@ -20,24 +20,39 @@ All the configuration, logs, coverage reports and data will be in `/tmp/pgmoneta
...
-To run one particular test case or suite (unfortunately check doesn't support running one single test at the moment), 
-run `CK_RUN_CASE=<test_case_name> <PATH_TO_PGMONETA>/pgmoneta/test/check.sh` or 
-`CK_RUN_SUITE=<test_case_name> <PATH_TO_PGMONETA>/pgmoneta/test/check.sh`. Alternatively, you can first export the environment variables 
-and then run the script:
+To run one particular test case or module, run `<PATH_TO_PGMONETA>/build/test/pgmoneta-test -t <test_case_name>` or 
+`<PATH_TO_PGMONETA>/build/test/pgmoneta-test -m <module_name>`. Alternatively, you can run the test binary directly:
 ```
-export CK_RUN_CASE=<test_case_name>
-<PATH_TO_PGMONETA>/pgmoneta/test/check.sh
+<PATH_TO_PGMONETA>/build/test/pgmoneta-test -t <test_case_name>
```
Comment (Jubilee101) [inline doc/TEST.md]: This doesn't make sense. You are repeating the line above.

File: doc/TEST.md [hunk 13]
```diff
@@ -20,24 +20,39 @@ All the configuration, logs, coverage reports and data will be in `/tmp/pgmoneta
...
+#include <mctf.h>
+#include <tscommon.h>
+
+MCTF_TEST(test_my_feature)
+{
+   pgmoneta_test_setup();
+
+   // Your test code here
+   int result = some_function();
+   MCTF_ASSERT(result == 0, "function should return 0", cleanup);
```
Comment (Jubilee101) [inline doc/TEST.md]: Would it be better if error label and message are swapped? something like `MCTF_ASSERT(result == 0, cleanup, "function should return 0, getting %d", result);`. And is message optional? Can we skip it or does it have to be NULL at least?

File: test/libpgmonetatest/mctf.c [hunk 14]
```diff
@@ -0,0 +1,374 @@
...
+         result->passed = false;
+         result->error_code = (ret != 0) ? ret : mctf_errno;
+         result->error_message = mctf_errmsg ? strdup(mctf_errmsg) : NULL;
+         if (mctf_errmsg)
+         {
+            free(mctf_errmsg);
+            mctf_errmsg = NULL;
+         }
+         g_runner.failed_count++;
+         printf("  %s (%02ld:%02ld:%02ld,%03ld) [FAIL] (error code: %d)\n",
```
Comment (Jubilee101) [inline test/libpgmonetatest/mctf.c]: Should it just be "line" instead of "error code"? That's what it is correct?

File: test/libpgmonetatest/mctf.c [hunk 15]
```diff
@@ -0,0 +1,374 @@
...
+   if (g_runner.failed_count > 0)
+   {
+      printf("\nFailed tests:\n");
+      for (size_t i = 0; i < g_runner.result_count; i++)
+      {
+         if (!g_runner.results[i].passed && !g_runner.results[i].skipped)
+         {
+            if (g_runner.results[i].error_message)
+            {
+               printf("  - %s (error code: %d) - %s\n",
```
Comment (Jubilee101) [inline test/libpgmonetatest/mctf.c]: Same comment, error code -> line perhaps, and it's better to include file name.

File: doc/TEST.md (hunk 13 above)
Comment (Jubilee101) [reply doc/TEST.md]: For the last question, I think either is fine, but we need to document it.

File: test/libpgmonetatest/mctf.c (hunk 15 above)
Comment (shashidhar-bm) [reply test/libpgmonetatest/mctf.c]: something like this?
```
Failed tests:
  - test_mctf_assert_with_message (test_mctf_assert.c:60) - value should be 10 but got 5
 ```

Comment (Jubilee101) [reply test/libpgmonetatest/mctf.c]: Yup. If you only keep track of module then printing that also works. Whichever is more convenient to you. The goal is that we can pinpoint what went wrong ASAP.

File: doc/TEST.md (hunk 13 above)
Comment (shashidhar-bm) [reply doc/TEST.md]: I swapped the parameters and made the message optional.

**Comment by shashidhar-bm** [comment]
@jesperpedersen , i'll update this pr with newly added tests in main.,

**Comment by jesperpedersen** [comment]
@shashidhar-bm Perfect, and resolve the conflicts too

**Comment by jesperpedersen** [comment]
@shashidhar-bm Share your thoughts on the patch overall once you have rebased

File: doc/TEST.md [hunk 16]
```diff
@@ -20,24 +20,45 @@ All the configuration, logs, coverage reports and data will be in `/tmp/pgmoneta
...
-run `CK_RUN_CASE=<test_case_name> <PATH_TO_PGMONETA>/pgmoneta/test/check.sh` or 
-`CK_RUN_SUITE=<test_case_name> <PATH_TO_PGMONETA>/pgmoneta/test/check.sh`. Alternatively, you can first export the environment variables 
-and then run the script:
-```
-export CK_RUN_CASE=<test_case_name>
-<PATH_TO_PGMONETA>/pgmoneta/test/check.sh
-```
-
-The environment variables will be automatically unset when the test is finished or aborted.
+To run one particular test case or module, run `<PATH_TO_PGMONETA>/build/test/pgmoneta-test -t <test_case_name>` or
```
Comment (Jubilee101) [inline doc/TEST.md]: Hmm, don't you still need check.sh to setup postgres and stuff?

Comment (shashidhar-bm) [reply doc/TEST.md]: oh, yes. i'll update it.

**Comment by shashidhar-bm** [comment]
> @shashidhar-bm Some times we get stuff like
> 
> ```
> pgmoneta-test: /home/runner/work/pgmoneta/pgmoneta/test/libpgmonetatest/tscommon.c:134: void pgmoneta_test_add_backup_chain(void): Assertion `!pgmoneta_tsclient_backup("primary", "newest")' failed.
> ./test/check.sh: line 325:  6644 Aborted                 (core dumped) $TEST_DIRECTORY/pgmoneta-test
> ```
> 
> That doesn't help much -- maybe have a signal handler that can give more information (pgmoneta_backtrace, and friends)

@jesperpedersen , I've added signal handlers to the test runner that display full backtraces

<details>
<summary>Signal Handlers </summary>

```text
test_utils_starts_with (00:00:00,000) [PASS]
test_resolve_path_trailing_env_var (00:00:00,000) [PASS]

--- signal_abrt ---
pgmoneta-test: /home/shashidhar/project/pgmoneta/test/testcases/test_signal_abrt.c:54: int test_signal_abrt_demo(void): Assertion `value == expected && "test_signal_abrt_demo: value should be 10"' failed.

========================================
FATAL: Received SIGABRT (assertion failure)
========================================

System: Linux 6.8.0

Backtrace:
#0  0x768fbc5aebf9 in pgmoneta_backtrace_string
        at /home/shashidhar/project/pgmoneta/src/libpgmoneta/utils.c:4904
#1  0x6341294484a5 in sigabrt_handler
        at /home/shashidhar/project/pgmoneta/test/runner.c:90
#2  0x768fbb645330 in __restore_rt
        at libc_sigaction.c:?
#3  0x768fbb69eb2c in __pthread_kill_implementation
        at ./nptl/./nptl/pthread_kill.c:44 (discriminator 1)
#4  0x768fbb64527e in __GI_raise
        at ./signal/../sysdeps/posix/raise.c:27
#5  0x768fbb6288ff in __GI_abort
        at ./stdlib/./stdlib/abort.c:81
#6  0x768fbb62881b in _nl_load_domain
        at ./intl/./intl/loadmsgcat.c:1177
#7  0x768fbb63b517 in __assert_fail
        at ??:?
#8  0x6341294b2222 in test_signal_abrt_demo
        at /home/shashidhar/project/pgmoneta/test/testcases/test_signal_abrt.c:54
#9  0x63412944af52 in mctf_run_tests
        at /home/shashidhar/project/pgmoneta/test/libpgmonetatest/mctf.c:284
#10  0x634129447aed in main
        at /home/shashidhar/project/pgmoneta/test/runner.c:249

========================================
./test/check.sh: line 315: 13543 Aborted                 (core dumped) $TEST_DIRECTORY/pgmoneta-test
Clean up
Shutdown pgmoneta
Header:
  ClientVersion: 0.20.0
  Command: shutdown
  Compression: zstd
  Encryption: aes-256-cbc
  Output: text
  Timestamp: 20260116225840
Outcome:
  Status: true
  Time: 00:00:0.0000
Request: {}
Cleaning up shared memory segments
Clean Test Resources
Coverage tools (llvm-profdata, llvm-cov) not found, skipping coverage report generation
Logs --> /tmp/pgmoneta-test/log, /tmp/pgmoneta-test/pg_log
Removing postgres 17 container
pgmoneta-test-postgresql17
pgmoneta-test-postgresql17
Unsetting environment variables

**Comment by shashidhar-bm** [comment]
@jesperpedersen, I looked for the new changes in test files in main, and I've updated in this branch as needed. 
Please help me, if I've missed anything in that

**Comment by jesperpedersen** [comment]
```
--- wal_summary ---
test_pgmoneta_wal_summary (00:00:00,017) [SKIP]
```

We should run all tests

**Comment by jesperpedersen** [comment]
@shashidhar-bm Add `test/include/` to the doxygen target in `doc/CMakeLists.txt` and document the APIs used

**Comment by shashidhar-bm** [comment]
> ```
> --- wal_summary ---
> test_pgmoneta_wal_summary (00:00:00,017) [SKIP]
> ```
> 
> We should run all tests

`wal_summary` module has only one test case, so there are no other tests to run when it skips

File: doc/CMakeLists.txt [hunk 17]
```diff
@@ -143,18 +143,15 @@ if (DOCS)
...
-    doxygen_add_docs(doxygen ${PROJECT_SOURCE_DIR}/src/include/)
+    doxygen_add_docs(doxygen ${PROJECT_SOURCE_DIR}/src/include/ ${PROJECT_SOURCE_DIR}/test/include/)
 
     if (${DOXYGEN_VERSION} STREQUAL "1.10.0" OR
         ${DOXYGEN_VERSION} STREQUAL "1.11.0" OR
         ${DOXYGEN_VERSION} STREQUAL "1.12.0" OR
         ${DOXYGEN_VERSION} STREQUAL "1.13.0" OR
         ${DOXYGEN_VERSION} STREQUAL "1.13.1" OR
         ${DOXYGEN_VERSION} STREQUAL "1.13.2" OR
-        ${DOXYGEN_VERSION} STREQUAL "1.14.0" OR
```
Comment (jesperpedersen) [inline doc/CMakeLists.txt:154]: Something went wrong here

File: test/testcases/test_wal_summary.c [hunk 18]
```diff
@@ -38,138 +39,375 @@
...
 #include <walfile.h>
 #include <walfile/wal_reader.h>
 #include <walfile/wal_summary.h>
+#include <mctf.h>
+
 #include <stdio.h>
+#include <stdlib.h>
+
+/* Forward declarations for helper functions specific to this test file */
+static void pgmoneta_test_cleanup_ssl(SSL** ssl);
```
Comment (jesperpedersen) [inline test/testcases/test_wal_summary.c:58]: Functions after includes

**Comment by jesperpedersen** [comment]
```
test/include/mctf.h:68: error: Member test_name (variable) of struct mctf_result is not documented.
test/include/mctf.h:69: error: Member file (variable) of struct mctf_result is not documented.
test/include/mctf.h:70: error: Member passed (variable) of struct mctf_result is not documented.
test/include/mctf.h:71: error: Member skipped (variable) of struct mctf_result is not documented.
test/include/mctf.h:72: error: Member error_code (variable) of struct mctf_result is not documented.
test/include/mctf.h:73: error: Member error_message (variable) of struct mctf_result is not documented.
test/include/mctf.h:79: error: Member tests (variable) of struct mctf_runner is not documented.
test/include/mctf.h:80: error: Member results (variable) of struct mctf_runner is not documented.
test/include/mctf.h:81: error: Member test_count (variable) of struct mctf_runner is not documented.
test/include/mctf.h:82: error: Member result_count (variable) of struct mctf_runner is not documented.
test/include/mctf.h:83: error: Member passed_count (variable) of struct mctf_runner is not documented.
test/include/mctf.h:84: error: Member failed_count (variable) of struct mctf_runner is not documented.
test/include/mctf.h:85: error: Member skipped_count (variable) of struct mctf_runner is not documented.
test/include/mctf.h:58: error: Member name (variable) of struct mctf_test is not documented.
test/include/mctf.h:59: error: Member module (variable) of struct mctf_test is not documented.
test/include/mctf.h:60: error: Member file (variable) of struct mctf_test is not documented.
test/include/mctf.h:61: error: Member func (variable) of struct mctf_test is not documented.
test/include/mctf.h:62: error: Member next (variable) of struct mctf_test is not documented.
```

**Comment by jesperpedersen** [comment]
@shashidhar-bm You broke `doc/CMakeLists.txt` - please, compare it to `main`

**Comment by shashidhar-bm** [comment]
@jesperpedersen Apologies for the delayed response
i've addressed the requested changes

**Comment by jesperpedersen** [comment]
```
test/libpgmonetatest/tscommon.c:86:20: runtime error: member access within null pointer of type 'struct main_configuration'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior test/libpgmonetatest/tscommon.c:86:20 
```

**Comment by jesperpedersen** [comment]
@shashidhar-bm Maybe add a function that will check that `main_configuration` is valid

**Comment by jesperpedersen** [comment]
```
test/libpgmonetatest/tscommon.c:90:20: runtime error: member access within null pointer of type 'struct main_configuration'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior test/libpgmonetatest/tscommon.c:90:20 
```

**Comment by shashidhar-bm** [comment]
> ```
> test/libpgmonetatest/tscommon.c:90:20: runtime error: member access within null pointer of type 'struct main_configuration'
> SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior test/libpgmonetatest/tscommon.c:90:20 
> ```

@jesperpedersen ,Could you share the exact command/environment where you see this error? I'm not reproducing it locally

**Comment by jesperpedersen** [comment]
@shashidhar-bm Fedora 43 w/ clang 21.x using `./test/check.sh` from top-level directory

**Comment by jesperpedersen** [comment]
@shashidhar-bm Can you recreate ?

**Comment by jesperpedersen** [comment]
`2026-01-22 22:11:01 DEBUG main.c:1032 Unencrypted request from localhost:[`

It says `[^Q\223^?`

**Comment by Jubilee101** [comment]
-- edit --
Maybe keep skip as is, but I don't think skip used on test setup failure is valid. Those tests should just fail. But it will be handy if we are developing new features and want to selectively turn off some new tests in case it trigger CI failure. Other than that, I'm happy about it. And I think we are close to taking it in. Thanks.

-- original comments --
@shashidhar-bm Getting https://gist.github.com/Jubilee101/448150cd8b288f9e30fc9fcf0b6a320a locally, so looks nice. We will look at the problem with test_wal_summary. Do you think you can make skip more informative? Maybe print out the line at which the test is skipped, rn it's a bit hard to know why the test is skipped. And it should probably still trigger CI pipeline failure, so that we can be alarmed. In the meantime please rebase, I had a minor update in check.sh setup. 

Cc @jesperpedersen

**Comment by Jubilee101** [comment]
> It says [^Q\223^?

@jesperpedersen  I have just
```
2026-01-23 16:10:26 DEBUG main.c:1032 Unencrypted request from localhost
```

**Comment by Jubilee101** [comment]
> @shashidhar-bm Fedora 43 w/ clang 21.x using ./test/check.sh from top-level directory

@jesperpedersen I have clang version 21.1.8 (Fedora 21.1.8-3.fc43), but I did not see this one

**Comment by jesperpedersen** [comment]
@shashidhar-bm Try and rebase and fix the conflict - then we will see where we are. Maybe my issues is separate from this PR

**Comment by jesperpedersen** [comment]
@shashidhar-bm Make sure that there are no skipped tests

**Comment by jesperpedersen** [comment]
@shashidhar-bm Did you rebase and fix the conflict ?

**Comment by shashidhar-bm** [comment]
I think new testcase has been added in main, I'll update pr again, adding it in mctf

**Comment by jesperpedersen** [comment]
@shashidhar-bm Currently you are next, so lets push a little to get it finished. Then we can look at improvements

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Comment by jesperpedersen** [comment]
@shashidhar-bm We need to look into 

```
--- wal_summary ---
test_pgmoneta_wal_summary (00:00:15,184) [SKIP]
```

**Comment by jesperpedersen** [comment]
@shashidhar-bm For now, look into improvements that can help to track down issues
