### PR TITLE
[#640]Fix Hash validation

### LINKED ISSUE #640: [Bug]hash mismatch logic
While reviewing the code in verify.c, I noticed a logic error involving the use of strcmp when comparing hash values. The current implementation uses:
```c
if (!strcmp(hash, calculated_hash))
{
  // hash mismatch
}
```

This condition is  incorrect if the intention is to detect mismatched hashes, since strcmp(a, b) returns 0 when strings are equal.

### PR DESCRIPTION
**Pull request by jchrys**
fixes #640

### CODE REVIEW

File: src/libpgmoneta/verify.c [hunk 1]
```diff
@@ -406,7 +406,7 @@ pgmoneta_sha512_verification(char** argv)
                goto cleanup;
             }
 
-            if (!strcmp(hash, calculated_hash))
+            if (strcmp(hash, calculated_hash))
```
Comment (jesperpedersen) [inline src/libpgmoneta/verify.c:409]: Lets do `!= 0`

**Review by jesperpedersen — CHANGES_REQUESTED** [review]

File: src/libpgmoneta/verify.c (hunk 1 above)
Comment (jchrys) [reply src/libpgmoneta/verify.c]: Sure :D

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !
